content: |-
  ## Global versionning rule for Claranet Azure modules
  
  | Module version | Terraform version | AzureRM version |
  | -------------- | ----------------- | --------------- |
  | >= 5.x.x       | 0.15.x & 1.0.x    | >= 2.0          |
  | >= 4.x.x       | 0.13.x            | >= 2.0          |
  | >= 3.x.x       | 0.12.x            | >= 2.0          |
  | >= 2.x.x       | 0.12.x            | < 2.0           |
  | <  2.x.x       | 0.11.x            | < 2.0           |

  ## Usage

  This module is optimized to work with the [Claranet terraform-wrapper](https://github.com/claranet/terraform-wrapper) tool
  which set some terraform variables in the environment needed by this module.
  More details about variables set by the `terraform-wrapper` available in the [documentation](https://github.com/claranet/terraform-wrapper#environment).

  ```hcl
  {{ include "examples/1/example.tf" }}
  ```

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
